
auth.token=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

defaults.org=g2-capture
defaults.project=react-native

defaults.url=https://sentry.io/
